### ISSUE TITLE
Active cluster writes

### ISSUE THREAD

**Issue by ligerard** [PureStorage-OpenConnect/pure-exporter#13]
In an active cluster the mirror write metrics for hosts and volumes doesn't exist .Is it possible to add them.
Another thing, the read metric is not OK on hosts. We have the value * 2 .

**Comment by genegr** [comment]
The new release v1.0.3 contains the additional metrics for the mirrored write. My guess about your other point is it relates to issues #8 and #9 and is fixed in all the versions.
