### ISSUE TITLE
Seeing multiple login sessions when running the FA collector

### ISSUE THREAD

**Issue by vishpat** [PureStorage-OpenConnect/pure-exporter#17]
While running the FlashArray collector, we saw the following alert for our array

**REST server is under the risk of becoming unresponsive**

This is because the FlashArray collector caused multiple login sessions on the array.

**Comment by vishpat** [comment]
I have opened a pull request [16](https://github.com/PureStorage-OpenConnect/pure-exporter/pull/16) with a possible fix for the issue.

**Comment by sdodsley** [comment]
@vishpat please sign the Pure Storage CLA before your PR can be assessed

**Comment by genegr** [comment]
Added the correct FlashArray session termination when the exporter object is deleted.
