### ISSUE TITLE
Export Flashblade Object Replica Link Metrics

### ISSUE THREAD

**Issue by zleinweber** [PureStorage-OpenConnect/pure-exporter#18]
In version 3.x of the Flashblade Firmware there is now an 'object replica link' feature. This feature can be used to replicate objects that are in a bucket on the flashblade to a remote target. The remote target can be either another flashblade or an alternative S3 target (like AWS S3).

Our organization uses object replica links to replicate data to offsite storage. We've already had several scenarios where these replica links have gotten into an unhealthy state and required manual intervention to fix. It would be nice to have metrics around this exported so that we can proactively alert in these types of scenarios.

I propose adding the following metrics for each object replica link:

- purefb_bucket_replica_links_replicating - (Gauge) 1 if replicating 0 otherwise
- purefb_bucket_replica_links_paused - (Gauge) 1 if paused 0 otherwise
- purefb_bucket_replica_links_unhealthy - (Gauge) 1 if unhealthy 0 otherwise
- purefb_bucket_replica_links_lag - (Gauge) Time in MS that the replication is behind
- purefb_bucket_replica_links_recovery_point - (Gauge) Unix time stamp to last full recovery point for the replica link

The relevant purity-fb documentation for this is: https://purity-fb.readthedocs.io/en/latest/BucketReplicaLinksApi/

**Comment by zleinweber** [comment]
For what it's worth, I've implemented this in https://github.com/zleinweber/pure-exporter/tree/object-replication-status. Will submit a PR.

**Comment by genegr** [comment]
Included in v1.2.1
