### ISSUE TITLE
Export quota metrics

### ISSUE THREAD

**Issue by mknapphrt** [PureStorage-OpenConnect/pure-exporter#20]
Hi guys,

Was wondering if it would be possible to have quota metrics added to the exporter? It seems to already exist in the purity-fb python client but I don't see anything exported from the exporter. Right now this is one of the few things blocking us from being able to fully cutover from this old exporter (https://github.com/man-group/prometheus-flashblade-exporter)

Thanks!

**Comment by genegr** [comment]
Hi @mknapphrt, I am going to add the proper handler for that among some other few new metrics.

**Comment by mknapphrt** [comment]
Hey @genegr, any update on this?

**Comment by genegr** [comment]
Included in v1.2.0
