### ISSUE TITLE
Export the exporter's metrics

### ISSUE THREAD

**Issue by finkr** [PureStorage-OpenConnect/pure-exporter#21]
It would be nice expose metrics about the exporter itself (cpu consumption, memory)
and expose some metrics about the collection itself (time spent collecting each kind of stuffs)

**Comment by finkr** [comment]
I wanted to work on this feature, but it's actually tricky, because a Gunicorn multi process model.

That's explained here:  https://github.com/prometheus/client_python#multiprocess-mode-gunicorn

**Comment by sdodsley** [comment]
pure-exporter deprecated as noted in README
