### ISSUE TITLE
 FlasharrayCollector: 'ConnectionError' object has no attribute 'message' 

### ISSUE THREAD

**Issue by finkr** [PureStorage-OpenConnect/pure-exporter#22]
The exporter occasionally fails with the following error:

    WARNING in pure_exporter: FlasharrayCollector: 'ConnectionError' object has no attribute 'message' 

Version : 1.0.3

Once it happens, the scape duration times out forever, until I restart the exporter.
The failure happens every few weeks.

My assumption so far is that there's a connection Error (connecting with http), but then we have this error: https://github.com/PureStorage-OpenConnect/rest-client/commit/30231639d7d700682c6ee054426c968c8cbbcfcb#r40240923

So we may need rest-client v1.19

**Comment by genegr** [comment]
Fixed in v1.2.2. This error was due to different/missing return values from Purity REST APIs versions.
