### ISSUE TITLE
Pure Storage FlashBlade system detail dashboard does not show any/correct values

### ISSUE THREAD

**Issue by florianmulatz** [PureStorage-OpenConnect/pure-exporter#40]
![image](https://user-images.githubusercontent.com/33655308/124239105-a68f3300-db19-11eb-8b3f-6d907d60575a.png)

**Comment by gloacai** [comment]
Purity//FB3.1.4

* Location: `site` is not a property in arrays so the panel needs to be deleted https://purity-fb.readthedocs.io/en/latest/PureArray/
* array name: this was fixed for me when I changed from `${DS_PROMETHEUS}` to `$datasource`
* firmware: this was fixed for me when I changed from `${DS_PROMETHEUS}` to `$datasource`
* hardware health: this was fixed for me when I changed from `${DS_PROMETHEUS}` to `$datasource`
* array capacity usage:  this was fixed for me when I changed from `${DS_PROMETHEUS}` to `$datasource`
* average iops: this was fixed for me when I changed from `${DS_PROMETHEUS}` to `$datasource`
* average latency: had to drop `,protocol="all"` from `sum(purefb_array_performance_latency_usec{job=~"$job",instance="$instance",protocol="all"}) / 1000` and that fixed it for me
* average throughput: this was fixed for me when I changed from `${DS_PROMETHEUS}` to `$datasource`

**Comment by sdodsley** [comment]
Resolved by #43
