### ISSUE TITLE
Pure Storage FlashBlade storage usage dashboard does not show any/correct values

### ISSUE THREAD

**Issue by florianmulatz** [PureStorage-OpenConnect/pure-exporter#41]
![image](https://user-images.githubusercontent.com/33655308/124239400-f0781900-db19-11eb-9c83-4a944e53f05c.png)

**Comment by florianmulatz** [comment]
same for storage usage detail

**Comment by gloacai** [comment]
May also be an issue for you. I'm using Grafana 7.0.6. I see that in the .json files they're referencing an input called DS_PROMETHEUS and some of the panels are using it for their `datasource`; this doesn't work for me and results in an empty panel.

sed'ing the file to change all instances of `${DS_PROMETHEUS}` to `$datasource` is getting more to display for me.

Now to figure out the why I'm not getting some iops metrics displaying but that's a different dashboard.

**Comment by sdodsley** [comment]
Resolved by #43
