### ISSUE TITLE
FlashArray dashboards use non-existent metric for average throughput

### ISSUE THREAD

**Issue by knack-roque** [PureStorage-OpenConnect/pure-exporter#44]
The `average throughput` panels on the dashboards show N/A because they're calculated on a non-existent metric of `purefa_array_performance_throughput_bytes﻿`. If it's supposed to be similar to the average volume throughput panels then I'd expect the query to be `sum (purefa_array_performance_bandwidth_bytes{job=~"$job", instance="$instance", volume="$volume"} )` or the metric name needs to change.

For now in my local copy I'm just going to change the dashboard to use the metric that exists since that's less effort for me.

**Comment by sdodsley** [comment]
pure-exporter deprecated as noted in README
