### ISSUE TITLE
Missing Metric 

### ISSUE THREAD

**Issue by jmg011** [PureStorage-OpenConnect/pure-exporter#50]
I have configured Prometheus server to scrape Pure exporter end-points for blade server. I see the metrics but I do not see this particular metric. Any idea why?

**Missing Metric**: purefb_array_capacity_bytes

**Available Metrics:** 

purefb_filesystem_performance_throughput_bytes
purefb_array_space_bytes
purefb_array_specific_performance_latency_usec
purefb_filesystem_user_usage_bytes
purefb_hw_status
purefb_info
purefb_array_performance_latency_usec
purefb_array_specific_performance_iops
purefb_filesystem_performance_iops
purefb_filesystems_data_reduction
purefb_filesystems_space_bytes
purefb_array_performance_throughput_bytes
purefb_array_performance_opns_bytes
purefb_array_space_data_reduction
purefb_filesystem_group_usage_bytes
purefb_filesystem_performance_latency_usec
purefb_filesystem_performance_opns_bytes
purefb_open_events_total
purefb_array_performance_iops

**I have configured these 3 metric path.**  Do I need to configure any other metrics path?

/metrics/flashblade/array
/metrics/flashblade/clients
/metrics/flashblade/usage

**Comment by vaddi** [comment]
We have the same issue, got a lot of metrics from all Endpoints, but missing **purefb_array_capacity_bytes**. So in the Dashboards a lot of Panels are unable to calculate without this metric.

**Comment by sdodsley** [comment]
@vaddi This exporter has been supeceeded by the new OpenMetrics exporter.
For FlashBlade you can find this here: https://github.com/PureStorage-OpenConnect/pure-fb-openmetrics-exporter
