### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by d3ployment** [PureStorage-OpenConnect/pure-exporter#51]
Hello, i'm trying to scrape metrics from my arrays but I get an error and I don't know why.
I think it's due to an error in my configuration.

I run pure-exporter and prometheus as docker services.
Here is my configuration file :

`
  - job_name: 'pure_flasharray'
    scrape_timeout: 15s
    metrics_path: /metrics/flasharray
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_endpoint
      - source_labels: [__pure_apitoken]
        target_label: __param_apitoken
      - source_labels: [__address__]
        target_label: instance
      - target_label: __address__
        replacement: pure-exporter:9491
    static_configs:
      - targets: [ 172.xx.xx.x ]
        labels:
          __pure_apitoken: << token >>
      - targets: [ 172.xx.xx.x ]
        labels:
          __pure_apitoken: << token >>
      - targets: [ 172.xx.xx.x ]
        labels:
          __pure_apitoken: << token >>
      - targets: [ 172.xx.xx.x ]
        labels:
          __pure_apitoken: << token >>
`

And here is the error I get in all prometheus targets : 

Get "http://172.xx.xx.x:80/metrics/flasharray?apitoken=<< token >>&endpoint=172.xx.xx.x": context deadline exceeded

Can anyone help me with this issue ?
Thanks in advance

**Comment by genegr** [comment]
Hi there,

Apparently the Prometheus server is not able to contact the exporter at the 172.xx.xx.x:80 ip and port. Did you try to issue the same request via curl from the same Prometheus machine? That just to confirm the target is reachable.

**Comment by d3ployment** [comment]
I figured it out earlier this morning and I replaced `pure-exporter:9091` by the IP of the service and it works but I now have another error : 

_server returned HTTP status 500 INTERNAL SERVER ERROR_

When I check in pure-exporter logs I can see something like this for each array :

 _WARNING in pure_exporter: FlashbladeCollector: Connection with FlashBlade 172.xx.xx.xx not initialized. Check array name/address and api-token_

**Comment by sdodsley** [comment]
You need to confirm the array IP addresses and associated API token are correct and as @genegr stated, the local Prometheus host must be able to `curl` to the IP addresses successfully.
Ensure that the firewalls are correctly configured, both on the host and any intermediate network firewalls.

**Comment by d3ployment** [comment]
From a swarm node (where Prometheus and pure-exporter are running) I can successfully curl IP but only with https and I get the Pure Sorage Login page
I'll try to change the scraping scheme to https
