### ISSUE TITLE
Missing Metric from metrics/flasharray/hosts endpoint

### ISSUE THREAD

**Issue by chrroberts-pure** [PureStorage-OpenConnect/pure-exporter#54]
The purefa_host_volumes_info metric is only available from most expensive /metrics/flasharray/ endpoint, I would expect it to also be available in /metrics/flasharray/hosts as well. 

Without this metric, it is hard to do correlation without the host, naaid table. It may also be helpful to add the volume name.

**Comment by chrroberts-pure** [comment]
Looking at purefa_host_volumes_info, this metric appears to be broken - it's only showing one naaid per host - when a host can be attached to multiple naaids.

I also think that host, volume would be more beneficial than host, naaid

I believe that naaid and volume is a 1:1 relationship

**Comment by sdodsley** [comment]
pure-exporter deprecated as noted in README
