### ISSUE TITLE
Suggestion to put the "info" metric into each endpoint for tagging purposes 

### ISSUE THREAD

**Issue by chrroberts-pure** [PureStorage-OpenConnect/pure-exporter#55]
On the FlashArray exporter - Currently only the /array endpoint contains "purefa_info"

# HELP purefa_info FlashArray system information
# TYPE purefa_info gauge
purefa_info{array_name="xxx",hostname="xxx",system_id="xxx",version="5.3.17"} 1.0

This would be very useful to use as a header on all endpoints for version tagging purposes.

**Comment by sdodsley** [comment]
pure-exporter deprecated as noted in README
