### ISSUE TITLE
Incorporate array_total_load function

### ISSUE THREAD

**Issue by mudaliar** [PureStorage-OpenConnect/pure-exporter#60]
In Pure1 manage portal --> "Analytics" --> Performance has a performance metrics which shows "Load" in percentage. Can the pure-exporter calculate or scrape this metric directly from the FA? I am aware that there is an API to pull this metrics from Pure1 portal itself but we would like to see this in real time.

**Comment by sdodsley** [comment]
There is no way to expose this number directly from the array.
It is calculated in Pure1 based on low-level drive performance data. Exposing this directly from the array would require too much compute/memory on the array to be feasible.
