### ISSUE TITLE
Unable to scrape "purefa_array_performance_throughput_bytes" metrics

### ISSUE THREAD

**Issue by mudaliar** [PureStorage-OpenConnect/pure-exporter#61]
I have installed the (quay.io/purestorage/pure-exporter:1.2.5-a) pure-exporter docker image. In this image it unable to scrape "purefa_array_performance_throughput_bytes" metrics. From the promql prompt it errors with "No datapoints found."

On the promql prompt the search shows only avg_block_bytes, bandwidth_bytes, latency_usec, qdepth as shown in the below screenshot.

![Screen Shot 2022-10-04 at 10 33 16 AM](https://user-images.githubusercontent.com/12573659/193887503-520b0104-81ca-4fca-9ba4-605a531b3d24.png)

**Comment by sdodsley** [comment]
Please note that this exporter is deprocated in favor of the OpenMetrics exporters for [FA](https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter) and [FB](https://github.com/PureStorage-OpenConnect/pure-fb-openmetrics-exporter). 

Please use the new version of the Exporter appropriate for your platform(s).
