### ISSUE TITLE
Pure Exporter doesn't report discards

### ISSUE THREAD

**Issue by JWThorne** [PureStorage-OpenConnect/pure-exporter#62]
We only see writes and reads. If you're able to tell the difference between write throughput for replicas, mirrored vs normal writes, surely you'd be able to report on discard traffic.

**Comment by sdodsley** [comment]
@JWThorne pure-exporter has been deprecated, as noted in the README.

If this issue is for the OpenMetrics Exporter, please raise it in the correct repo.
