### ISSUE TITLE
FlashBlade hardware never marked as healthy

### ISSUE THREAD

**Issue by zleinweber** [PureStorage-OpenConnect/pure-exporter#8]
Small typo here causes the check on whether FlashBlade hardware is healthy to fail:
https://github.com/PureStorage-OpenConnect/pure-exporter/blob/4fa422f79339e579da4ebd96626b4dc448b0bbad/collectors/flashblade.py#L79

'healty' should be 'healthy'. Not sure what the appropriate way to go about flagging this is so I created an issue. If I should have done this differently let me know.

**Comment by genegr** [comment]
Fixed by merging the PR
