### ISSUE TITLE
FlashBlade _input_ops named _output_ops

### ISSUE THREAD

**Issue by zleinweber** [PureStorage-OpenConnect/pure-exporter#9]
The exporter seems to export the `purefb_perf_output_ops` metric twice. I think one of these is supposed to be input_ops. The typo appears to be on line:

https://github.com/PureStorage-OpenConnect/pure-exporter/blob/4fa422f79339e579da4ebd96626b4dc448b0bbad/collectors/flashblade.py#L326

**Comment by genegr** [comment]
Fixed the typo. Should export the right metric name now/
